version: '3.7'
services:
  opa_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/home/node/app'
    entrypoint: ./.docker/entrypoint.sh
    environment:
      - NODE_ENV=development
    ports:
      - '4200:4200'
      - '9230:9229'
      - '9876:9876'
